[package]
name = "leetcode_rust"
version = "0.1.0"
authors = ["ITOAR"]
edition = "2018"

[[bin]]
name = "rust_main"
path="src/main.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies] 
